DROP TABLE SERVER CASCADE CONSTRAINTS;
DROP TABLE FRIEND CASCADE CONSTRAINTS;
DROP TABLE APPUSER CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE CASCADE CONSTRAINTS;
DROP TABLE USER_ROLE_GIVEN CASCADE CONSTRAINTS;
DROP TABLE USER_DEFAULT_STATUS CASCADE CONSTRAINTS;
DROP TABLE FRIEND_REQUEST CASCADE CONSTRAINTS;

CREATE TABLE APPUSER ( --사용자 테이블
  APPUSER_ID VARCHAR2(36), --사용자 식별자 (PK)
  APPUSER_UK_NAME VARCHAR2(20) , --사용자 고유 이름  (UK)
  APPUSER_DISPLAY_NAME VARCHAR2(20), --사용자 디스플레이 이름(ui에서 메인으로 보여지는 이름)
  APPUSER_EMAIL VARCHAR2(20), -- 사용자 이메일 (UK)
  APPUSER_PASSWORD VARCHAR2(35), -- 비밀번호
  APPUSER_REG_DATE DATE DEFAULT SYSDATE, -- 등록날짜
  APPUSER_GEN_PFP VARCHAR2(50), -- 사용자 프사(기본 프사)
  APPUSER_ABOUT VARCHAR(100), -- 서버 유저 소개
  PRIMARY KEY(APPUSER_ID),
  CONSTRAINT APPUSER_UK_NAME_UK UNIQUE(APPUSER_UK_NAME),
  CONSTRAINT APPUSER_EMAIL_UK UNIQUE(APPUSER_EMAIL)
);

CREATE TABLE FRIEND_REQUEST(
  FRIEND_REQUEST_SENDER VARCHAR2(36),
  FRIEND_REQUEST_RECEIVER VARCHAR2(36),
  PRIMARY KEY(FRIEND_REQUEST_SENDER, FRIEND_REQUEST_RECEIVER),
  FOREIGN KEY (FRIEND_REQUEST_SENDER)
    REFERENCES APPUSER(APPUSER_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (FRIEND_REQUEST_RECEIVER)
    REFERENCES APPUSER(APPUSER_ID)
    ON DELETE CASCADE
);

CREATE TABLE FRIEND( -- 친구 테이블
  FRIEND1 VARCHAR2(36), -- 친구1 (FK: 사용자아이디) 
  FRIEND2 VARCHAR2(36), -- 친구2 (FK: 사용자아이디)
  -- PK: 친구1, 친구2
  PRIMARY KEY(FRIEND1, FRIEND2),
  FOREIGN KEY (FRIEND1)
    REFERENCES APPUSER(APPUSER_ID)
    ON DELETE CASCADE,
  FOREIGN KEY (FRIEND2)
    REFERENCES APPUSER(APPUSER_ID)
    ON DELETE CASCADE
);

CREATE TABLE SERVER( -- 서버 테이블
  SERVER_ID VARCHAR2(36), -- 서버 아이디 (PK)
  SERVER_NAME VARCHAR2(36), -- 서버 이름 (UK)
  SERVER_OWNER VARCHAR2(36), -- 서버 오너 (FK: 사용자아이디) 
  SERVER_DESC VARCHAR(80), -- 서버 소개
  SERVER_REG_DATE DATE, -- 서버 등록 날짜
  SERVER_PFP VARCHAR2(60), -- 서버 프사
  PRIMARY KEY (SERVER_ID),
  FOREIGN KEY (SERVER_OWNER)
    REFERENCES APPUSER(APPUSER_ID)
    ON DELETE CASCADE
);



CREATE TABLE USER_ROLE( -- 역할
    USER_ROLE_ID VARCHAR2(36), -- 역할 아이디 (PK)
    USER_ROLE_NAME VARCHAR2(40), -- 역할 이름 (UK)
    USER_ROLE_SERVER VARCHAR2(36), -- 서버 (FK: 서버아이디)
    PRIMARY KEY (USER_ROLE_ID),
    FOREIGN KEY(USER_ROLE_SERVER)
        REFERENCES SERVER(SERVER_ID)
        ON DELETE CASCADE,
    CONSTRAINT ROLE_USER_NAME_SERVER_UK UNIQUE(USER_ROLE_NAME, USER_ROLE_SERVER)
);

CREATE TABLE USER_ROLE_GIVEN( -- 주어진 역할 (사용자에게 주어진)
    USER_ROLE_GIVEN_ROLE VARCHAR2(36), -- 역할 (FK: 역할 아이디) 
    USER_ROLE_GIVEN_USER VARCHAR2(36), -- 사용자 (FK: 사용자 아이디)
    -- PK: 역할, 사용자
    PRIMARY KEY(USER_ROLE_GIVEN_ROLE, USER_ROLE_GIVEN_USER),
    FOREIGN KEY(USER_ROLE_GIVEN_ROLE)
        REFERENCES USER_ROLE(USER_ROLE_ID)
        ON DELETE CASCADE,
    FOREIGN KEY(USER_ROLE_GIVEN_USER)
        REFERENCES APPUSER(APPUSER_ID)
        ON DELETE CASCADE
);

CREATE TABLE USER_DEFAULT_STATUS( -- 사용자 디폴트 상태 테이블 (온라인, 오프라인, 방해금지 등등)
  USER_DEFAULT_STATUS_USER VARCHAR2(36), -- 사용자(PK, FK)
  USER_DEFAULT_STATUS_STATUS VARCHAR2(15), -- 상태
  PRIMARY KEY(USER_DEFAULT_STATUS_USER),
  FOREIGN KEY(USER_DEFAULT_STATUS_USER)
      REFERENCES APPUSER(APPUSER_ID)
      ON DELETE CASCADE
);




